-- public.exam_results definition
-- Drop table
-- DROP TABLE public.exam_results;

create table public.exam_results (
	id int8 generated by default as identity( increment by 1 minvalue 1 maxvalue 9223372036854775807 start 1 cache 1 no cycle) not null,
	quiz_id int8 not null,
	score int4 not null,
	submitted_at timestamp(6) not null,
	user_id int8 not null,
	evidence jsonb null,
	constraint exam_results_pkey primary key (id)
);
-- public.quizzes definition
-- Drop table
-- DROP TABLE public.quizzes;

create table public.quizzes (
	id int8 generated by default as identity( increment by 1 minvalue 1 maxvalue 9223372036854775807 start 1 cache 1 no cycle) not null,
	created_at timestamp(6) not null,
	description text null,
	title varchar(200) not null,
	constraint quizzes_pkey primary key (id)
);

create index idx_quiz_title on
public.quizzes
    using btree (title);
-- public.users definition
-- Drop table
-- DROP TABLE public.users;

create table public.users (
	id int8 generated by default as identity( increment by 1 minvalue 1 maxvalue 9223372036854775807 start 1 cache 1 no cycle) not null,
	created_at timestamp(6) not null,
	"password" varchar(255) not null,
	"role" varchar(20) not null,
	username varchar(50) not null,
	constraint idx_username unique (username),
	constraint users_pkey primary key (id),
	constraint users_role_check check (((role)::text = any ((array['ADMIN'::character varying,
'USER'::character varying])::text[])))
);
-- public.notifications definition
-- Drop table
-- DROP TABLE public.notifications;

create table public.notifications (
	id int8 generated by default as identity( increment by 1 minvalue 1 maxvalue 9223372036854775807 start 1 cache 1 no cycle) not null,
	created_at timestamp(6) not null,
	is_read bool not null,
	message varchar(500) not null,
	user_id int8 not null,
	constraint notifications_pkey primary key (id),
	constraint fk9y21adhxn0ayjhfocscqox7bh foreign key (user_id) references public.users(id)
);
-- public.questions definition
-- Drop table
-- DROP TABLE public.questions;

create table public.questions (
	id int8 generated by default as identity( increment by 1 minvalue 1 maxvalue 9223372036854775807 start 1 cache 1 no cycle) not null,
	correct_answer varchar(255) not null,
	details jsonb null,
	"type" varchar(50) not null,
	quiz_id int8 not null,
	constraint questions_pkey primary key (id),
	constraint fkn3gvco4b0kewxc0bywf1igfms foreign key (quiz_id) references public.quizzes(id)
);
